apiVersion: v1
kind: Pod
metadata:
  labels:
    run: host-pod
  name: host-pod
spec:
  containers:
  - image: nginx
    name: host-pod
    volumeMounts:
    - name: data
      mountPath: /test-sravan
  
  volumes:
  - name: data
    hostPath:
            path: /home
  

    
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
