apiVersion: v1
kind: PersistentVolume
metadata:
  name: sravan-pv-volume
  labels:
    type: local
  namespace: vol
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home"
