apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: vol1
  name: vol1
  namespace: vol
spec:
  containers:
  - image: nginx
    name: vol1
    volumeMounts:
    - name: data
      mountPath: /sravan-test
  volumes:
  - name: data
    emptyDir: {}
