apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: 3containers-pods
  name: 3containers-pods
spec:
  containers:
  - image: busybox
    name: 1con
    args:
            - /bin/sh
            - -c
            - sleep 400
  
  - image: busybox
    name: 2-con
    command: ["/bin/sh", "-c", "sleep 400"]
  - name: 3-container
    image: busybox
    args:
            - echo this is the trid 3 contianrer



    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
