apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    env: prod
  name: 3podsnnode2
spec:
  containers:
  - image: nginx
    name: nginx
  - image: redis
    name: redis
  - image: tomcat
    name: tomcat
  nodeSelector:
    type: ssd


  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
