apiVersion: v1
kind: Pod
metadata:
  labels:
    run: after-init
  name: after-init
spec:
  containers:
  - image: nginx
    name: after-init



  initContainers:
  - image: busybox
    name: demo-init1
    command: ['sh', '-c', 'until nslookup myservice; do echo waiting for myservice;done']
