apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: cm-subject
spec:
  containers:
  - image: busybox:latest
    name: cm-subject
    ports:
    - containerPort: 80
    command: ['sh', '-c', 'echo this is running && sleep 3600']
    env:
       - name: NAMEOFSUB
         valueFrom:
            configMapKeyRef:
               name: subject
               key: name
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
