apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: enamypod
  name: enamypod
spec:
  containers:
  - image: nginx
    name: enamypod
    env:
       - name: ENEMY_NAME
         valueFrom:
           configMapKeyRef:
              name: game.properties
              key: enemies
            
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
