apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: envar
  name: envar
  namespace: ngx
spec:
  containers:
  - image: busybox:latest
    name: envar
    args:
       - sleep
       - "3600"
    env:
       - name: PLANET
         value: "blue"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
