apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: envar2
  name: envar2
  namespace: ngx
spec:
  containers:
  - image: nginx:latest
    name: envar2
    env:
      - name: DEMO_GREETING
        value: "Hello from the environment"
      - name: DEMO_FAREWELL
        value: "Such a sweet sorrow"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
