apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: envar1
  name: envar1
  namespace: ngx
spec:
  containers:
  - image: busybox:latest
    name: envar1
    env:
      - name: COLOR
        value: "blue"
      - name : COLOR2
        value: "this si red color"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
