apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: game-config-pod
  name: game-config-pod
  namespace: ngx
spec:
  containers:
  - image: nginx:1.16
    name: game-config-pod
    env:
       - name: GAMEVALUE
         valueFrom:
                 configMapKeyRef:
                         name: game-prop
                         key: lives

    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
