apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: geo-pod
  name: geo-pod
  namespace: ngx
           
spec:
  containers:
  - image: nginx
    name: geo-pod
    env:
       - name: LOCATION
         valueFrom:
             configMapKeyRef: 
                name: geo
                key: location

    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
