apiVersion: v1
kind: Pod
metadata:
  name: after-init
spec:
  containers:
  - image: busybox
    name: after-init
    commmand: ['sh', '-c', 'echo its running']
  initContainers:
  - image: busybox
    name: init-my-sleep
    command: ['sh', '-c', 'sleep 30']
