apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: affinity
  name: node-affinity
spec:
  containers:
  - image: nginx
    name: node-affinity
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  affinity:
    nodeAffinity:
   	requiredDuringSchedulingIgnoredDuringExecution:
           nodeSelectorTerms:
           - matchExpressions:    
             - key: type        
               operator: In  
               values:
	       - ssd   

status: {}
