apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset1
  namespace: new2
 
spec:
  selector:
     matchLabels: 
        name: daemonset1
  template:
    metadata:
      labels:
        name: daemonset1
    spec:
      containers:
      - name: daemonset1
        image: busybox
        args:
           - sleep
           - "3600"
