apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: podallenv
  name: podallenv
  namespace: new2
spec:
  containers:
  - image: nginx
    name: podallenv
    envFrom:
        - configMapRef:
            name: cmfromfileenv
  restartPolicy: Never
status: {}
