apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: podenvfile123
  name: podenvfile123
  namespace: new2
spec:
  containers:
  - name: nginx1
    image: nginx
    env:
       - name: variablefromconfigmap
         valueFrom:
                 configMapKeyRef:
                           key: name
                           name: cmfromfileenv
       - name: variablefromconfigmap222      
         valueFrom:
                 configMapKeyRef:
                           key: cmfile1 
                           name: cmfromfile
        
  restartPolicy: Never
